#!/usr/bin/env python3
"""合并场景目录里所有 meta.yaml 的 prerequisites.python 为一份 requirements。

用法：collect_env_requirements.py <envs_path> [<envs_path> ...] > requirements-envs.generated.txt

字段缺省视为无额外依赖；非法形状（不是字符串列表）报错退出，宁可构建失败也
不要静默漏装。只依赖 PyYAML。
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml


def python_prerequisites(meta: dict) -> list[str]:
    prereqs = meta.get("prerequisites")
    if not isinstance(prereqs, dict):
        return []
    raw = prereqs.get("python")
    if raw is None:
        return []
    if not isinstance(raw, list) or not all(isinstance(x, str) and x.strip() for x in raw):
        raise ValueError("prerequisites.python 必须是非空字符串列表")
    return [x.strip() for x in raw]


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__, file=sys.stderr)
        return 2
    merged: dict[str, str] = {}
    for root in argv:
        for meta_path in sorted(Path(root).glob("*/meta.yaml")):
            try:
                meta = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
                for req in python_prerequisites(meta):
                    merged.setdefault(req, meta_path.parent.name)
            except Exception as exc:  # noqa: BLE001
                print(f"{meta_path}: {exc}", file=sys.stderr)
                return 1
    print("# generated by collect_env_requirements.py — do not edit")
    for req, env_name in sorted(merged.items()):
        print(f"{req}  # {env_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
